version: '3'

services:
  backend:
    image: cw-anti-fraud-api
    build:
      context: ./backend # This is going to be the "root" of the build and it uses the Dockfile in it
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
