require: rubocop-rails

AllCops:
  NewCops: enable

# Metrics
Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
    Exclude:
        - spec/**/*
        - db/**/*

# Rails
Rails/Output:
  Exclude:
    - db/**/*

# Styles
Style/Documentation:
  Enabled: false
Style/BlockComments:
  Exclude:
    - spec/**/*